#!/usr/bin/env node
/**
 * scorecard.mjs — Phase 0 (P0-XR-06)
 *
 * Aggregates the deterministic artifact-verify results (and, once wired, the
 * agent-runner K2–K4 results) into the program scorecard: KPIs K1–K10 from the
 * Master Plan. Emits docs/ai-agent-readiness/SCORECARD.md and scorecard.json.
 *
 * Deterministic KPIs (available now): K1, K5, K8, K10.
 * Agent-driven KPIs (need the runner + secrets): K2, K3, K4 -> PENDING_RUNNER.
 * Depth KPIs (delivered in Phase 3): K6, K7 -> PENDING_PHASE3.
 *
 * Usage: node tools/agent-harness/scorecard.mjs   (or: npm run verify:scorecard)
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const OUT_DIR = join(REPO, 'docs', 'ai-agent-readiness');
const AV_JSON = join(OUT_DIR, 'artifact-verify.json');
const LANGS = ['rust', 'python', 'dart', 'csharp', 'javascript'];

/**
 * Load artifact-verify results. Preferred (CI-friendly): read the JSON emitted
 * by `verify.mjs --out docs/ai-agent-readiness/artifact-verify.json`. Fallback:
 * spawn the verifier directly. Decoupling avoids a nested child-process spawn
 * and lets the scorecard regenerate offline from the last verify run.
 */
function loadArtifactVerify() {
  if (existsSync(AV_JSON)) {
    return JSON.parse(readFileSync(AV_JSON, 'utf-8'));
  }
  try {
    const raw = execFileSync('node', [join(REPO, 'tools', 'artifact-verify', 'verify.mjs'), '--json'], {
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
      maxBuffer: 8 * 1024 * 1024,
    });
    return JSON.parse(raw);
  } catch (e) {
    if (e.stdout) return JSON.parse(e.stdout.toString()); // verifier exits 1 when FAILs present
    throw new Error(
      `No ${AV_JSON} found and could not spawn verify.mjs (${e.message}). ` +
        `Run: node tools/artifact-verify/verify.mjs --out docs/ai-agent-readiness/artifact-verify.json`,
    );
  }
}

const av = loadArtifactVerify();
const by = (lang, id) => av.results.find((r) => r.lang === lang && r.id === id);

// 2) Derive KPIs
const namePass = LANGS.filter((l) => by(l, 'NAME_PARITY')?.status === 'PASS');
const k1 = `${namePass.length}/5 install-name parity (proxy for verbatim quickstart)`;
const llmsPass = LANGS.filter((l) => by(l, 'LLMS_TXT')?.status === 'PASS');
const versionParity = by('fleet', 'VERSION_PARITY');
// Docs-vs-artifact drift = name/type/exports/llms mismatches, NOT fleet version parity (that is K8).
const DRIFT_IDS = ['NAME_PARITY', 'TYPE_SIGNALS', 'EXPORTS_RESOLVE', 'LLMS_TXT'];
const driftFail = av.results.some((r) => DRIFT_IDS.includes(r.id) && r.status === 'FAIL');

const kpis = [
  { id: 'K1', name: 'Quickstart-verbatim (install-name parity)', value: k1,
    status: namePass.length === 5 ? 'GREEN' : 'RED', target: '5/5' },
  { id: 'K2', name: 'Task first-try pass rate', value: 'PENDING_RUNNER', status: 'PENDING', target: '>= 90%' },
  { id: 'K3', name: 'Turns-to-first-tx', value: 'PENDING_RUNNER', status: 'PENDING', target: '<= 6' },
  { id: 'K4', name: 'Human interventions per task', value: 'PENDING_RUNNER', status: 'PENDING', target: '<= 0.2' },
  { id: 'K5', name: 'API-ingestion coverage (llms.txt shipped)', value: `${llmsPass.length}/5`,
    status: llmsPass.length === 5 ? 'GREEN' : 'RED', target: '5/5 (Phase 2)' },
  { id: 'K6', name: 'Typed-surface ratio', value: 'PENDING_PHASE3', status: 'PENDING', target: '100%' },
  { id: 'K7', name: 'Error-actionability', value: 'PENDING_PHASE3', status: 'PENDING', target: '>= 95%' },
  { id: 'K8', name: 'Fleet version parity', value: versionParity?.detail || '?',
    status: versionParity?.status === 'PASS' ? 'GREEN' : 'RED', target: '1 minor line' },
  { id: 'K9', name: 'MCP installable in <= 1 config block', value: 'accumulate-studio-mcp@1.0.0 on npm',
    status: 'GREEN', target: 'published' },
  { id: 'K10', name: 'Docs-vs-artifact drift (artifact-verify)', value: driftFail ? 'drift present' : 'clean',
    status: driftFail ? 'RED' : 'GREEN', target: 'CI-gated, 0 drift' },
];

// 3) Per-language snapshot
const perLang = LANGS.map((l) => ({
  lang: l,
  version: (by(l, 'VERSION')?.detail.match(/@ ([^\s]+)/) || [])[1] || '?',
  name_parity: by(l, 'NAME_PARITY')?.status || '-',
  type_signals: by(l, 'TYPE_SIGNALS')?.status || '-',
  exports: by(l, 'EXPORTS_RESOLVE')?.status || '-',
  llms: by(l, 'LLMS_TXT')?.status || '-',
}));

// 4) Emit
const stamp = new Date().toISOString().slice(0, 10);
const icon = { GREEN: '🟢', RED: '🔴', PENDING: '⚪' };
const sIcon = { PASS: '✅', FAIL: '❌', EXPECTED_FAIL: '🔶', SKIP: '⚠️', INFO: 'ℹ️', '-': '·' };

let md = `# Accumulate AI-Agent Readiness — Scorecard\n\n`;
md += `> Generated by \`tools/agent-harness/scorecard.mjs\` from \`artifact-verify\`. `;
md += `Deterministic KPIs (K1, K5, K8, K10) are live now; agent-driven KPIs (K2–K4) and depth KPIs (K6, K7) light up as the runner (Phase 0) and Phase 3 land.\n\n`;
md += `**Baseline date:** ${stamp}\n\n`;

md += `## KPIs\n\n| KPI | Metric | Status | Value | Target |\n|---|---|:--:|---|---|\n`;
for (const k of kpis) md += `| ${k.id} | ${k.name} | ${icon[k.status]} | ${k.value} | ${k.target} |\n`;

md += `\n## Per-language artifact snapshot\n\n| Lang | Version | Name parity | Type signals | Exports | llms.txt |\n|---|---|:--:|:--:|:--:|:--:|\n`;
for (const p of perLang)
  md += `| ${p.lang} | ${p.version} | ${sIcon[p.name_parity]} | ${sIcon[p.type_signals]} | ${sIcon[p.exports]} | ${sIcon[p.llms]} |\n`;

md += `\n## Legend\n\n`;
md += `- 🟢 green · 🔴 red · ⚪ pending measurement\n`;
md += `- ✅ pass · ❌ fail · 🔶 expected-fail (delivered in a later phase) · ⚠️ skip · ℹ️ info · · n/a\n\n`;
md += `## How to reproduce\n\n\`\`\`bash\nnpm run verify:artifacts     # raw artifact checks\nnpm run verify:scorecard     # regenerate this file\n\`\`\`\n`;

writeFileSync(join(OUT_DIR, 'SCORECARD.md'), md);
writeFileSync(
  join(OUT_DIR, 'scorecard.json'),
  JSON.stringify({ baselineDate: stamp, kpis, perLang, artifactVerify: av }, null, 2),
);

console.log(`Wrote docs/ai-agent-readiness/SCORECARD.md and scorecard.json (baseline ${stamp}).`);
const greens = kpis.filter((k) => k.status === 'GREEN').length;
const reds = kpis.filter((k) => k.status === 'RED').length;
const pend = kpis.filter((k) => k.status === 'PENDING').length;
console.log(`KPIs: ${greens} green, ${reds} red, ${pend} pending measurement.`);
