/**
 * Project Scaffolds - Generate language-specific project structures
 *
 * Each `generate{Lang}Project` produces the project's metadata files (package
 * manifests, READMEs) plus a single main source file generated by the unified
 * manifest engine (`generateCodeFromManifest`). There is no second, hand-written
 * code generator: the downloaded project's code is identical to the Studio
 * preview, for all 25 block types across all languages.
 */

import type { Flow, GeneratedFile, SDKLanguage, SDKMap } from '@accumulate-studio/types';
import { generateCodeFromManifest } from './manifest-generator';
import { loadAllManifests } from './manifest-loader';

// =============================================================================
// Unified engine accessor
// =============================================================================

// Manifests are static data bundled at build time; load once.
const MANIFESTS = loadAllManifests();

/** Resolve the manifest for a language, falling back to the JS manifest for TS. */
function manifestFor(language: SDKLanguage): SDKMap | null {
  if (MANIFESTS[language]) return MANIFESTS[language]!;
  if (language === 'typescript' && MANIFESTS['javascript']) return MANIFESTS['javascript']!;
  return null;
}

/** Single source of truth for the main source body — the unified manifest engine. */
function mainSource(flow: Flow, language: SDKLanguage): string {
  return generateCodeFromManifest(flow, language, 'sdk', manifestFor(language));
}

// =============================================================================
// Types
// =============================================================================

export interface ProjectGenerator {
  (flow: Flow): GeneratedFile[];
}

// =============================================================================
// Python Project Generator
// =============================================================================

export function generatePythonProject(flow: Flow): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const safeName = toSnakeCase(flow.name);

  // pyproject.toml
  files.push({
    path: 'pyproject.toml',
    content: `[project]
name = "${safeName}"
version = "0.1.0"
description = "${flow.description ?? `Accumulate flow: ${flow.name}`}"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accumulate-sdk-opendlt==2.0.2",
    "requests>=2.31",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
`,
  });

  // Main Python file (generated by the unified manifest engine)
  files.push({
    path: `${safeName}/main.py`,
    content: mainSource(flow, 'python'),
    isEntryPoint: true,
  });

  // __init__.py — re-export the engine-A entry point (`main`)
  files.push({
    path: `${safeName}/__init__.py`,
    content: `"""${flow.name} - Generated by Accumulate Studio"""

from .main import main

__all__ = ["main"]
`,
  });

  // README.md
  files.push({
    path: 'README.md',
    content: generatePythonReadme(flow, safeName),
  });

  return files;
}

function generatePythonReadme(flow: Flow, safeName: string): string {
  return `# ${flow.name}

${flow.description ?? 'Generated by Accumulate Studio'}

## Installation

\`\`\`bash
pip install -e .
\`\`\`

## Environment Variables

${flow.variables.map((v) => `- \`${v.name.toUpperCase()}\`: ${v.description ?? v.type}${v.required === false ? ' (optional)' : ''}`).join('\n') || 'No environment variables required.'}

## Usage

\`\`\`bash
python -m ${safeName}.main
\`\`\`

Or as a library:

\`\`\`python
from ${safeName} import main

main()
\`\`\`

## Generated by Accumulate Studio

This project was automatically generated from a visual flow definition.
`;
}

// =============================================================================
// Rust Project Generator
// =============================================================================

export function generateRustProject(flow: Flow): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const safeName = toSnakeCase(flow.name);

  // Cargo.toml — dependencies aligned with the Rust templates' `use` statements.
  files.push({
    path: 'Cargo.toml',
    content: `[package]
name = "${safeName}"
version = "0.1.0"
edition = "2021"
description = "${flow.description ?? `Accumulate flow: ${flow.name}`}"

[dependencies]
accumulate-sdk = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde_json = "1"
sha2 = "0.10"
hex = "0.4"
url = "2"
`,
  });

  // Main Rust file (generated by the unified manifest engine)
  files.push({
    path: 'src/main.rs',
    content: mainSource(flow, 'rust'),
    isEntryPoint: true,
  });

  // README.md
  files.push({
    path: 'README.md',
    content: generateRustReadme(flow, safeName),
  });

  return files;
}

function generateRustReadme(flow: Flow, _safeName: string): string {
  return `# ${flow.name}

${flow.description ?? 'Generated by Accumulate Studio'}

## Build

\`\`\`bash
cargo build --release
\`\`\`

## Environment Variables

${flow.variables.map((v) => `- \`${v.name.toUpperCase()}\`: ${v.description ?? v.type}${v.required === false ? ' (optional)' : ''}`).join('\n') || 'No environment variables required.'}

## Usage

\`\`\`bash
cargo run
\`\`\`

## Generated by Accumulate Studio

This project was automatically generated from a visual flow definition.
`;
}

// =============================================================================
// Dart Project Generator
// =============================================================================

export function generateDartProject(flow: Flow): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const safeName = toSnakeCase(flow.name);

  // pubspec.yaml — deps aligned with the Dart templates' imports.
  files.push({
    path: 'pubspec.yaml',
    content: `name: ${safeName}
description: ${flow.description ?? `Accumulate flow: ${flow.name}`}
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  opendlt_accumulate: ^0.1.0
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.24.0
`,
  });

  // Main Dart file (generated by the unified manifest engine). Named after the
  // package so `dart run` (no args) finds it.
  files.push({
    path: `bin/${safeName}.dart`,
    content: mainSource(flow, 'dart'),
    isEntryPoint: true,
  });

  // README.md
  files.push({
    path: 'README.md',
    content: generateDartReadme(flow, safeName),
  });

  return files;
}

function generateDartReadme(flow: Flow, _safeName: string): string {
  return `# ${flow.name}

${flow.description ?? 'Generated by Accumulate Studio'}

## Installation

\`\`\`bash
dart pub get
\`\`\`

## Environment Variables

${flow.variables.map((v) => `- \`${v.name.toUpperCase()}\`: ${v.description ?? v.type}${v.required === false ? ' (optional)' : ''}`).join('\n') || 'No environment variables required.'}

## Usage

\`\`\`bash
dart run
\`\`\`

## Generated by Accumulate Studio

This project was automatically generated from a visual flow definition.
`;
}

// =============================================================================
// JavaScript/TypeScript Project Generator
// =============================================================================

export function generateJavaScriptProject(flow: Flow): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const safeName = toKebabCase(flow.name);

  // package.json — dependency aligned with the JS templates' import.
  files.push({
    path: 'package.json',
    content: JSON.stringify(
      {
        name: safeName,
        version: '0.1.0',
        description: flow.description ?? `Accumulate flow: ${flow.name}`,
        type: 'module',
        main: 'src/index.js',
        scripts: {
          start: 'node src/index.js',
        },
        dependencies: {
          'accumulate.js': '^0.12.0',
        },
      },
      null,
      2
    ),
  });

  // Main JS file (generated by the unified manifest engine)
  files.push({
    path: 'src/index.js',
    content: mainSource(flow, 'javascript'),
    isEntryPoint: true,
  });

  // README.md
  files.push({
    path: 'README.md',
    content: generateJavaScriptReadme(flow, safeName),
  });

  return files;
}

function generateJavaScriptReadme(flow: Flow, _safeName: string): string {
  return `# ${flow.name}

${flow.description ?? 'Generated by Accumulate Studio'}

## Installation

\`\`\`bash
npm install
\`\`\`

## Environment Variables

${flow.variables.map((v) => `- \`${v.name.toUpperCase()}\`: ${v.description ?? v.type}${v.required === false ? ' (optional)' : ''}`).join('\n') || 'No environment variables required.'}

## Usage

\`\`\`bash
npm start
\`\`\`

## Generated by Accumulate Studio

This project was automatically generated from a visual flow definition.
`;
}

// =============================================================================
// C# Project Generator
// =============================================================================

export function generateCSharpProject(flow: Flow): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const safeName = toPascalCase(flow.name);

  // <Name>.csproj — package aligned with the C# templates' `using` statements.
  files.push({
    path: `${safeName}.csproj`,
    content: `<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>${safeName}</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Acme.Net.Sdk" Version="0.1.*" />
  </ItemGroup>

</Project>
`,
  });

  // Program.cs (generated by the unified manifest engine)
  files.push({
    path: 'Program.cs',
    content: mainSource(flow, 'csharp'),
    isEntryPoint: true,
  });

  // README.md
  files.push({
    path: 'README.md',
    content: generateCSharpReadme(flow, safeName),
  });

  return files;
}

function generateCSharpReadme(flow: Flow, _safeName: string): string {
  return `# ${flow.name}

${flow.description ?? 'Generated by Accumulate Studio'}

## Build

\`\`\`bash
dotnet build
\`\`\`

## Environment Variables

${flow.variables.map((v) => `- \`${v.name.toUpperCase()}\`: ${v.description ?? v.type}${v.required === false ? ' (optional)' : ''}`).join('\n') || 'No environment variables required.'}

## Usage

\`\`\`bash
dotnet run
\`\`\`

## Generated by Accumulate Studio

This project was automatically generated from a visual flow definition.
`;
}

// =============================================================================
// Utility Functions
// =============================================================================

function toSnakeCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, '_')
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '')
    .replace(/_+/g, '_');
}

function toKebabCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, '-')
    .replace(/([A-Z])/g, '-$1')
    .toLowerCase()
    .replace(/^-/, '')
    .replace(/-+/g, '-');
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, '_')
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

// =============================================================================
// Generator Registry
// =============================================================================

export const PROJECT_GENERATORS: Record<SDKLanguage, ProjectGenerator> = {
  python: generatePythonProject,
  rust: generateRustProject,
  dart: generateDartProject,
  javascript: generateJavaScriptProject,
  typescript: generateJavaScriptProject, // TypeScript uses the JS generator + manifest
  csharp: generateCSharpProject,
};

/**
 * Generate a project for the specified language
 */
export function generateProject(flow: Flow, language: SDKLanguage): GeneratedFile[] {
  const generator = PROJECT_GENERATORS[language];
  if (!generator) {
    throw new Error(`No project generator available for language: ${language}`);
  }
  return generator(flow);
}
